### ISSUE TITLE
Elastic Repos 

### ISSUE THREAD

**Issue by thorteschenk** [NETWAYS/ansible-collection-elasticstack#106]
Hi,

Elastic Repos should be disabled by default (enabled=0), so that it is not updated with os updates.

In each roles at point installation they should be enabled explicit with enablerepo parameter.

**Comment by widhalmt** [comment]
Thanks for the feedback!

We can add this as an option. So you can add the repositories in an disabled state. I believe, most users rely on the repositories being enabled by default. But you do have a good point. Given that Elastic introduces breaking changes quite often, it's a good idea to have them disabled.

I just don't want to set our defaults to something, users won't expect. But I'll integrate an option to allow disabling/enabling them on demand and I'll dedicate a section in Readme to Update handling.

**Comment by widhalmt** [comment]
PR #108 contains code that might allow this scenario. It's not really a draft but it might need some more work.
