### ISSUE TITLE
Restarting Elasticsearch after the first start is not ideal

### ISSUE THREAD

**Issue by afeefghannam89** [NETWAYS/ansible-collection-elasticstack#141]
We flush handlers in security file yaml after the first start of the new initialized cluster. That lead to directly restart of Elasticsearch after the first start. This is maybe not ideal. We can put a when condition to adjust this behavior. 

Also, we put two tasks to start Elasticsearch. The first one in security file yaml and the next one in main.yml. This led to two changes in Ansible output. What about putting when condition to not trigger the second one if security is enabled?

What do you think @widhalmt?

**Comment by widhalmt** [comment]
I'd love to minimize restarts. The current version is just the outcome of sometimes needing Elasticsearch running and sometimes not. If you find a better way, I'm all for it. Maybe the current way isn't needed any more due to all the changes we had.
