### ISSUE TITLE
Enhancement: Use FQCN for Tasks

### ISSUE THREAD

**Issue by dnssmr** [NETWAYS/ansible-collection-elasticstack#178]
I know, some people like the FQCN and some hate them, but i'd like to refactor the repository to use the FQCN since Ansible recommends it to avoid conflicting with other collections that may have the same module name.

**Comment by widhalmt** [comment]
Well, I *do* hate them. And even some people who contribute regularly to Ansible hate them. But as you know, I'm always ok with change if we can people make happy. Let's hear what others who contribute to this repository, think.

I'd prefer to ignore FQCN but if only the two of us raise their voice, I'm ready to go with your approach.
