### ISSUE TITLE
Take out lint jobs from all workflows to a separated one

### ISSUE THREAD

**Issue by afeefghannam89** [NETWAYS/ansible-collection-elasticstack#192]
It will be good to take out all lint jobs from all workflows files and build a separated linter workflow. Other corresponding workflows will only run if linter workflows ended successfully. What we achieve with this?

01- Compact code
02- Now, many pipelines/workflows will run if a change happens on `.config/ansible-lint.yml` or `.yamllint`. Only linter pipeline should be run in this case.

**Comment by widhalmt** [comment]
Yes. I agree with you. Separate linters only give overhead but as you said, it's just about a few seconds.

Having linters in the specific jobs and running a linter in the same pipeline before the whole tests only makes sense, if we bring back `fail-fast`. As I understand, GitHub will stop executing pipelines when one check has failed. This has drawbacks and benefits. But if we bring it back, running a linter before a pipeline helps with not wasting ressources for checks that won't work anyway.

**Comment by Donien** [comment]
I've created a [branch](https://github.com/NETWAYS/ansible-collection-elasticstack/tree/fix/lint-workflow-192) to test using a reusable workflow for linting.  

- When changing linting rules, the **whole repo** is linted using `yamllint .` and all roles are linted using `ansible-lint roles/`.  
- When changing something about a role (e.g. kibana), **only the role** is linted using `yamllint roles/kibana` and `ansible-lint roles/kibana`. This happens as the first job within the given (role specific) workflow.
- Drawback: When changing something about the rules themselves and about a role at the same time, two workflows will trigger; one for the general linting and one for the role specific changes (one for each role that is). Thus, in edge cases there would be a bit more overhead.

This is just a first draft on how this could be done.  
If you have any ideas or suggestions on how to better deal with the issue, please let me know.
