### ISSUE TITLE
Has something changed with ansible galaxy?

### ISSUE THREAD

**Issue by stevedwray** [NETWAYS/ansible-collection-elasticstack#206]
Is this a typo or something in your instructions?
The very first command fails:
steve@EXE:~/workspace/ansible/vm-prep$ ansible-galaxy collection install https://github.com/netways/ansible-collection-elasticstack.git
Downloading https://github.com/netways/ansible-collection-elasticstack.git to /home/steve/.ansible/tmp/ansible-local-4826huprjt81/tmpqfmbqeml/ansible-collection-elasticst-6fj14m0k
ERROR! Collection artifact at '/home/steve/.ansible/tmp/ansible-local-4826huprjt81/tmpqfmbqeml/ansible-collection-elasticst-6fj14m0k/ansible-collection-elasticstack.git' is not a valid tar file.

**Comment by martialblog** [comment]
Hi,

the `ansible-galaxy` command expects the name of the role/collection and looks for it at https://galaxy.ansible.com/

If you want to download something via git you have to prefix the URL with `git+`

`ansible-galaxy collection install git+https://github.com/netways/ansible-collection-elasticstack.git`

Alternatively, you can specify downloads in a YAML file (again with type git):

```yaml
collections:
  - name: https://github.com/organization/repo_name.git
    type: git
    version: devel
```

https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html

**Comment by stevedwray** [comment]
Great, I didn't know that. So the documentation does have a typo:
`ansible-galaxy collection install https://github.com/netways/ansible-collection-elasticstack.git`

**Comment by martialblog** [comment]
Indeed. That should be fixed!

Thanks for the hint!
