### ISSUE TITLE
Read installed version and use as new default

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-collection-elasticstack#236]
Elastic Stack doesn't like having different versions of services throughout one setup.

What about the following:
* If you don't give a certain version to install, we install the latest one available in the repository. Just like now
* With every Ansible run after the first, we read the installed version (e.g. from the CA host) and use this as the new default

This way we could make sure that new hosts always have the correct version, even when they are set up some time after the initial setup.

**Comment by lcndsmr** [comment]
Yes, please.
If I understand correctly, if you would install beats with the collection some time after you install the stack, you could get a newer version of the beats? That'd be bad. We should implement a way to check the installed version.
