### ISSUE TITLE
Logstash hashing breaks idempotency?

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-collection-elasticstack#247]
The hashing in https://github.com/NETWAYS/ansible-collection-elasticstack/blob/main/roles/logstash/templates/logstash_writer_user.j2#L3 seems to break idempotency. So I had to deactivate it for Molecule in #243 .

This issue is for investigating if there really is a problem with the hashing. e.g. creating different hashes with repeated runs. Maybe this will also help with solving #186

**Comment by DanOPT** [comment]
The password_hash function uses a random string as salt if no secret string is provided. https://docs.ansible.com/ansible/latest/collections/ansible/builtin/password_hash_filter.html

That breaks the logic of Jinja templates and the ansible.builtin.template module, since it will always returns a hash with a random salt. 

We could allow to specify a secret sting for the salt, optionally and ommitable, of course. I already tested it. If the salt is specified, the same hash will be returned.

However, I don't know how much sense this makes regarding security. That probably makes only sense for idempotency.

**Comment by widhalmt** [comment]
Then, we either should safe the salt somewhere or, maybe even better, just use a default and tell users to change it. And I think, idempotency is a very valid reason for implementing this.

**Comment by DanOPT** [comment]
I'm not sure. The salt should always be random. So simply a default var is not a good idea. I probably would omit in every case, except for the pipelines?

**Comment by widhalmt** [comment]
Why would you want to use a random salt every time? Maybe I missed something but when the salt is sufficiently random and long, it should be enough. Having a new random salt every time will change the template for the user everytime and will lead to the user being re-created or changed with every Ansible run.

**Comment by widhalmt** [comment]
@afeefghannam89 the original code is from you. So *ping* :-)

**Comment by widhalmt** [comment]
@DanOPT I can think of two options to make it a bit more robust and not relying on the user to change the variable:

* Generate a random hash but saving it in a file. So we can reuse it. @afeefghannam89 had a solution that could do just that. We just needed to change the path of the hashfile from `/dev/null`.
* Introducing a complexity check for the hash. Downside: We either force the user to generate one or we provide one that's complex enough (but will still be the same default in every installation)

So the first one seems to be a bit more reasonable to me.

**Comment by DanOPT** [comment]
@widhalmt 
> Why would you want to use a random salt every time? Maybe I missed something but when the salt is sufficiently random and long, it should be enough. Having a new random salt every time will change the template for the user everytime and will lead to the user being re-created or changed with every Ansible run.

Yes, you are right. It should be _globally unique_. So every password should have it's own random salt. I didn't get that, that's why I said I'm not sure.

> So the first one seems to be a bit more reasonable to me.
I agree, that's absolutely fine to save the a salted hash to a file. It would be saved in a file anyway.

**Comment by widhalmt** [comment]
Ah, ok. Now I'm get. To be honest, I did wonder if I was mistaken and was searching for a situation where having a changing salt would be beneficial. So creating one and saving it might be the best option. I'll adapt the PR.

**Comment by afeefghannam89** [comment]
@widhalmt unfortunately we can not use SHA-256 without changing the default hashing algorithm by Elasticsearch which is bcrypt see here https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#password-hashing-settings
Changing this default may cause braking somewhere in elastic. So I would stay using bcrypt and not change it to SHA-256.  I think they prefer bcrypt over SHA-256 for the following reason:

SHA-256, in particular, benefits a lot from being implemented on a GPU. Thus, if you use SHA-256-crypt, attackers will be more at an advantage than if you use bcrypt, which is hard to implement efficiently in a GPU.

**Comment by afeefghannam89** [comment]
If you use SHA-256 without changing the default elasticsearch password hashing algorithm **bcrypt** you will get the same error which Denies had here https://github.com/NETWAYS/ansible-collection-elasticstack/pull/186#issuecomment-1614385105

**Comment by widhalmt** [comment]
Thanks for the hint. I totally lost that. I'll change it right away.
