### ISSUE TITLE
Should we introduce an extra role for collection wide variables?

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-collection-elasticstack#286]
Like in https://stackoverflow.com/questions/67213727/ansible-collections-collection-level-variable we could build a role called `elasticstack`. This will only hold `defaults/main.yml` and `README.md`. All variables we use in all roles could be set there. So we had them in a central place to change and document. And we could get rid of those pesky linter messages about variable names not matching role names.

**Comment by ivareri** [comment]
My first thought was that you meant a new repo with just a single role, but you're thinking of an extra role in this repo? 

I do think this seems like a clean solution. As long as it is the same repo it shouldn't add any extra burden on contributors and reviewers.

**Comment by widhalmt** [comment]
Yes, I'm thinking of a role in this very repo. Like `roles/elasticstack` . And have all "global" variables in there.
