### ISSUE TITLE
Re-enable tests on rpm based distros

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-collection-elasticstack#327]
### Describe the feature request

We had to disable tests on rpm based distros due to a bug. (See https://github.com/NETWAYS/ansible-collection-elasticstack/pull/326 for details). When 8.14.1 is released we should try to re-enable these checks.

**Comment by tbauriedel** [comment]
Elasticsearch v8.14.1 has been released.
https://github.com/elastic/elasticsearch/releases/tag/v8.14.1

At the moment there isnt a Changelog available, but we should check if there is an fix applied already.

Ping @widhalmt

**Comment by widhalmt** [comment]
Thanks. I'll look into it.
