### ISSUE TITLE
[Bug]: Daemon reload command is missing after Logstash install

### ISSUE THREAD

**Issue by frankhetterich** [NETWAYS/ansible-collection-elasticstack#342]
### Please try to fill out as much of the information below as you can. Thank you!

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Describe the bug

We have updated our Logstash instances to Version 8.15.0 and with that update the Unit file of the Logstash service was modified so that a systemctl daemon-reload is needed. 

The Collection is using a handler  in "roles/logstash/handlers/main.yml" and  here the additional parameter "daemon-reload: true" should be added to both handlers.

### How to recreate the bug?

Modify the unit file with some additional text, perform a daemon-reload and afterwards update or reinstall Logstash with the collection

**Comment by widhalmt** [comment]
Good find, again. Thanks. Fix is coming up!

**Comment by widhalmt** [comment]
Thanks for the suggested code. I used it in the fix.

Since we're not managing the unit file from the collection it's totally fine to change its contents. So this is a valid request.
