### ISSUE TITLE
`set_output` in actions is deprecated.

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-collection-elasticstack#85]
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for details

**Comment by DanOPT** [comment]
Can't find any set-output or set-state commands in the workflow files. Is it already fixed?

**Comment by widhalmt** [comment]
No. Sorry, I don't have more information that I found some deprecation warnings when running workflows. 🤷🏽

**Comment by widhalmt** [comment]
fixed with #111
