### ISSUE TITLE
`docker` input only works on filebeat < 8

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-collection-elasticstack#86]
Release 8.x of Filebeat doesn't have a `docker` input anymore. We need to provide a working solution for `7` and `8`.

Please make sure they are correctly documented (without the current warning) in `docs/role-beats.md`. And the checks reenabled in the `beats_peculiar` Molecule scenario.

**Comment by widhalmt** [comment]
NOTE: The warning is currently missing and the check is still activated. But this will change as soon as #55 is merged.

**Comment by dnssmr** [comment]
Is this still up to date?

**Comment by widhalmt** [comment]
Honestly, I lost track. :-( The mentioned PR is merged. So I guess, it's fixed. I'll close the issue. Please keep `docker` input in mind. If we hit it again, we can re-open the issue.
