### ISSUE TITLE
Wait for Elasticsearch to start should be modified

### ISSUE THREAD

**Issue by afeefghannam89** [NETWAYS/ansible-collection-elasticstack#95]
```
TASK [netways.elasticstack.elasticsearch : Fail if cluster is not ready yet] ****************************************************************************************************************************************************************************************************************
fatal: [elasticcollection-1]: FAILED! => {"changed": false, "msg": "Elasticsearch cluster is not ready (status: yellow , yet. Please rerun again later."}
fatal: [elasticcollection-2]: FAILED! => {"changed": false, "msg": "Elasticsearch cluster is not ready (status: yellow , yet. Please rerun again later."}
fatal: [elasticcollection-3]: FAILED! => {"changed": false, "msg": "Elasticsearch cluster is not ready (status: yellow , yet. Please rerun again later."}
```

**Comment by widhalmt** [comment]
What do you suggest? Longer timeouts?

**Comment by afeefghannam89** [comment]
I suggest to use curl or use until as a parameter with more tries for example 5

**Comment by afeefghannam89** [comment]
It is the same issue here #100 When I rerun the playbook then the task is ok. The message in log say it is authentication failure, what make man wondering. What do you think about resolving first the timeout issue, then see if the authentication problem exists?

**Comment by widhalmt** [comment]
Yes, sound like a good idea! Please don't use `curl` with `command` or `shell`. If we want to check directly, maybe `get_url` or similar modules work. If they don't, maybe it's time to start to build a module to check the status of Elasticsearch?

**Comment by widhalmt** [comment]
Well... considering the code we already have, maybe using `curl` won't be as bad. ;-) I'm ok with staying with `curl` for now and planning a better solution for *all* curls we have for a future rework.

**Comment by widhalmt** [comment]
Thanks for the suggestion with `until`. That makes the whole code a lot better, I guess.
